apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: kserve-storage-initializer-29
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: kserve-storage-initializer-29
    app.kubernetes.io/part-of: kserve-storage-initializer
  name: kserve-storage-initializer-29
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app.kubernetes.io/instance: kserve-storage-initializer-29
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: kserve-storage-initializer-29
    spec:
      containers:
      - image: quay.io/modh/kserve-storage-initializer@sha256:4d373d424bedb66e59b33561c3a100f233483c2217832880dbc59e423fe3aa2a
        imagePullPolicy: Always
        name: container-image
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 10m
            memory: 256Mi
status: {}
