apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: kserve-storage-initializer-28
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/modh/kserve-storage-initializer@sha256:9307c6d60f62e3fad68e9748401e26d8b07dc3cb7665042f9ac4d9536ea889d7
        name: container-image
        resources: {}
status: {}
