apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: kserve-storage-initializer-28
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/rhoai-tenant/kserve-storage-initializer/kserve-storage-initializer-28@sha256:6be439afb370ff44b8bd4d2f12b1ff3eee8d29b7fab9563c4d05cb2a620b1899
        name: container-image
        resources: {}
status: {}
