apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: kserve-storage-initializer
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: kserve-storage-initializer
    app.kubernetes.io/part-of: kserve-storage-initializer
  name: kserve-storage-initializer
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app.kubernetes.io/instance: kserve-storage-initializer
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: kserve-storage-initializer
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/rhoai-tenant/kserve-storage-initializer/kserve-storage-initializer@sha256:4920c9f6531a7448bdc4ff9f772528e22f87f68819e36e04c7af9ae15e83d99b
        imagePullPolicy: Always
        name: container-image
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 10m
            memory: 256Mi
status: {}
