apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: kserve-storage-initializer-28
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: kserve-storage-initializer-28
    app.kubernetes.io/part-of: kserve-storage-initializer
  name: kserve-storage-initializer-28
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app.kubernetes.io/instance: kserve-storage-initializer-28
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: kserve-storage-initializer-28
    spec:
      containers:
      - image: quay.io/modh/kserve-storage-initializer@sha256:ae6419a5b94a6a9baad7dfe5a52284ab5ef8fda0fb4d069442dccc05d3708f37
        imagePullPolicy: Always
        name: container-image
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 10m
            memory: 256Mi
status: {}
