apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: kserve-storage-initializer-28
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: kserve-storage-initializer-28
    app.kubernetes.io/part-of: kserve-storage-initializer
  name: kserve-storage-initializer-28
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app.kubernetes.io/instance: kserve-storage-initializer-28
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: kserve-storage-initializer-28
    spec:
      containers:
      - image: quay.io/modh/kserve-storage-initializer@sha256:4dd010925fb4cde0b7b663bd86023320cf8ef886750e727f18107ef7afd0c8a9
        imagePullPolicy: Always
        name: container-image
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 10m
            memory: 256Mi
status: {}
