apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: kserve-storage-initializer
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/rhoai-tenant/kserve-storage-initializer/kserve-storage-initializer@sha256:cd295cb517e26797dbf87dd5b4e98aa4af469e861ad96d53b77aa1ee9c172402
        name: container-image
        resources: {}
status: {}
